export const cards = [
  {
    id: 1,
    title: "Web Design",
    desc: "Create stunning websites",
    img: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 2,
    title: "WordPress",
    desc: "Customize your WordPress site",
    img: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 3,
    title: "Logo Design",
    desc: "Build your brand identity",
    img: "https://images.pexels.com/photos/442779/pexels-photo-442779.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 4,
    title: "Digital Marketing",
    desc: "Expand your online presence",
    img: "https://images.pexels.com/photos/159888/pexels-photo-159888.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 5,
    title: "AI Services",
    desc: "Harness the power of AI",
    img: "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 6,
    title: "Graphic Design",
    desc: "Create visual concepts",
    img: "https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 7,
    title: "Video",
    desc: "Create engaging videos",
    img: "https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 8,
    title: "Animation",
    desc: "Bring stories to life",
    img: "https://images.pexels.com/photos/1563355/pexels-photo-1563355.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 9,
    title: "Writing",
    desc: "Craft compelling stories",
    img: "https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 10,
    title: "Translation",
    desc: "Bridge language gaps",
    img: "https://images.pexels.com/photos/159761/books-college-conceptual-reading-159761.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 11,
    title: "Music",
    desc: "Compose beautiful melodies",
    img: "https://images.pexels.com/photos/164926/pexels-photo-164926.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 12,
    title: "Audio",
    desc: "Perfect sound quality",
    img: "https://images.pexels.com/photos/1727202/pexels-photo-1727202.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 13,
    title: "Programming",
    desc: "Write clean and efficient code",
    img: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 14,
    title: "Tech",
    desc: "Innovate with cutting-edge technology",
    img: "https://images.pexels.com/photos/256467/pexels-photo-256467.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 15,
    title: "Business",
    desc: "Grow your business efficiently",
    img: "https://images.pexels.com/photos/3184296/pexels-photo-3184296.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 16,
    title: "Lifestyle",
    desc: "Enhance your way of life",
    img: "https://images.pexels.com/photos/3656856/pexels-photo-3656856.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 17,
    title: "Game Development",
    desc: "Create immersive games",
    img: "https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 18,
    title: "SEO",
    desc: "Boost your website ranking",
    img: "https://images.pexels.com/photos/7110/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 19,
    title: "Data Science",
    desc: "Unlock the value of data",
    img: "https://images.pexels.com/photos/3184299/pexels-photo-3184299.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 20,
    title: "Photo Editing",
    desc: "Enhance your images",
    img: "https://images.pexels.com/photos/40765/woman-face-eyes-view-40765.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 21,
    title: "Mobile App Development",
    desc: "Build modern mobile apps",
    img: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 22,
    title: "E-commerce Development",
    desc: "Develop scalable e-commerce",
    img: "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 23,
    title: "Social Media Management",
    desc: "Grow your online community",
    img: "https://images.pexels.com/photos/267389/pexels-photo-267389.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 24,
    title: "Content Writing",
    desc: "Craft compelling content",
    img: "https://images.pexels.com/photos/3184464/pexels-photo-3184464.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 25,
    title: "Illustration",
    desc: "Bring ideas to life visually",
    img: "https://images.pexels.com/photos/3778241/pexels-photo-3778241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 26,
    title: "3D Modeling",
    desc: "Create realistic 3D models",
    img: "https://images.pexels.com/photos/6222/nature-sunny-red-flowers.jpg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 27,
    title: "Voice Over",
    desc: "Deliver impactful messages",
    img: "https://images.pexels.com/photos/3761509/pexels-photo-3761509.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 28,
    title: "Online Tutoring",
    desc: "Learn with expert tutors",
    img: "https://images.pexels.com/photos/4035757/pexels-photo-4035757.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 29,
    title: "Virtual Assistance",
    desc: "Get expert help remotely",
    img: "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 30,
    title: "Project Management",
    desc: "Manage projects effectively",
    img: "https://images.pexels.com/photos/669610/pexels-photo-669610.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
];


export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://cdn.pixabay.com/photo/2023/04/04/14/19/boy-7899447_1280.jpg",
    cat: "Web and Mobile Design",
    username: "Anurag",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.nightcafe.studio/jobs/K1eCGcNHH24f00khNzHC/K1eCGcNHH24f00khNzHC--1--cg8nh.jpg?tr=w-1600,c-at_max",
    cat: "Logo Design",
    username: "Aayush",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiVqgIW-da1wcZlwMP3jnqhAMnkBcTfBfEMDT2G-at14-AYXgE8ZDmDyFbnkJy7G_UFYs&usqp=CAU",
    cat: "Animated GIFs",
    username: "Genius",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://cdn.pixabay.com/photo/2024/03/16/10/29/ai-generated-8636783_1280.jpg",
    cat: "Packaging Design",
    username: "Adarsh",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://imgcdn.stablediffusionweb.com/2024/4/22/c17ece2f-f1e6-408f-ac96-de93b53d4c88.jpg",
    cat: "Social Media Design",
    username: "Bhuwan",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://img.freepik.com/premium-photo/cartoon-boy-with-messy-haircut-hoodie-generative-ai_1028873-12768.jpg",
    cat: "Illustration",
    username: "Joyti",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBYm2q6uEv8rjvz_aEgnkmNJiz0auLiZjlGYhT7SQ4khN82mLO3f3GEMwy9D2WGfkQ5IE&usqp=CAU",
    cat: "Book Design",
    username: "Aaditya",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXZ659yQh6iRycPikh9MmF0Yu_re_ewEVU2w&s",
    cat: "Digital Marketing",
    username: "Mohit",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://cdn.pixabay.com/photo/2023/04/04/14/19/boy-7899447_1280.jpg",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anurag",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.nightcafe.studio/jobs/K1eCGcNHH24f00khNzHC/K1eCGcNHH24f00khNzHC--1--cg8nh.jpg?tr=w-1600,c-at_max",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Aayush",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiVqgIW-da1wcZlwMP3jnqhAMnkBcTfBfEMDT2G-at14-AYXgE8ZDmDyFbnkJy7G_UFYs&usqp=CAU",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Genius",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://cdn.pixabay.com/photo/2024/03/16/10/29/ai-generated-8636783_1280.jpg",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Adarsh",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://imgcdn.stablediffusionweb.com/2024/4/22/c17ece2f-f1e6-408f-ac96-de93b53d4c88.jpg",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Bhuwan",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://img.freepik.com/premium-photo/cartoon-boy-with-messy-haircut-hoodie-generative-ai_1028873-12768.jpg",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Jyoti",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBYm2q6uEv8rjvz_aEgnkmNJiz0auLiZjlGYhT7SQ4khN82mLO3f3GEMwy9D2WGfkQ5IE&usqp=CAU",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Aaditya",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXZ659yQh6iRycPikh9MmF0Yu_re_ewEVU2w&s",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Mohit",
  },
];
